# https://www.appveyor.com/docs/appveyor-yml/
image: Visual Studio 2017

platform:
  - x64

environment:
  GITHUB_TOKEN:
    secure: prCF4R95zHBf+wzqA5PE9bPkM0aLhS8FcUyQYOMENjiwySn9fFlRtSrrtp7zznkG
  matrix:
    - nodejs_version: 10


cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules -> package.json
  - scripts/node_modules -> scripts/package.json
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off
test: on
deploy: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn

test_script:
  - echo Start app testing...
  - yarn run test

deploy_script:
  - echo Start app building...
  - yarn install
  - yarn build
  - cd scripts
  - yarn install
  - publish-release.cmd
